'use client';

// import type { Metadata } from 'next';

import { Toaster } from 'react-hot-toast';

import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import HashtagLayout from '@/components/Layouts/HashtagLayout';
import { useGetUser } from '@/hooks/user';
import { LoggedInUserContext } from '@/context/LoggedInUserContext';
import { PostContext } from '@/context/PostContext';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { user, status } = useGetUser();
  return (
    <LoggedInUserContext.Provider value={{ user, status }}>
      <HashtagLayout>
    
          {children}
     
      </HashtagLayout>
      <Toaster /> <ReactQueryDevtools initialIsOpen={false} />
    </LoggedInUserContext.Provider>
  );
}
