'use client';

// import type { Metadata } from 'next';

import { Toaster } from 'react-hot-toast';

import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import HashtagLayout from '@/components/Layouts/HashtagLayout';
import { useGetUser } from '@/hooks/user';
import { LoggedInUserContext } from '@/context/LoggedInUserContext';
import { useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const router = useRouter();
  const { user, status } = useGetUser();
  const [authenticated, setAuthenticated] = useState(false);

  useEffect(() => {
    if (status === 'success' && user?.id) {
      setAuthenticated(true);
    } else if (status === 'success' && !user?.id) {
      setAuthenticated(false);
      router.push('/');
    }
  }, [status, user]);

  if (!authenticated) {
    return null;
  }

  return (
    <LoggedInUserContext.Provider value={{ user, status }}>
      <HashtagLayout>{children}</HashtagLayout>
      <Toaster /> <ReactQueryDevtools position="left" initialIsOpen={false} />
    </LoggedInUserContext.Provider>
  );
}
